# Generated by Django 3.2.8 on 2021-11-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Soc', '0002_alter_student_ic_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_no',
            field=models.CharField(max_length=100, verbose_name='No. Telefon'),
        ),
    ]
