# Generated by Django 3.2.8 on 2021-11-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Soc', '0003_alter_student_phone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('ic_no', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='IC No.')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('phone_no', models.CharField(max_length=100, verbose_name='Phone Number')),
            ],
        ),
    ]
