# Generated by Django 3.2.8 on 2021-11-19 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Soc', '0004_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
